### ISSUE TITLE
Asset Downloader is completely broken

### ISSUE THREAD

**Issue by ThePartyGoat224** [SoDOff-Project/sodoff-tools#1]
no matter how much i try the config file won't download, the example config section is poorly written and should be in a separate file and i cant even path download because it ends up in a "no content length in response error".

**Comment by rpaciorek** [comment]
The configuration file (or url to it) should be received from the administrator / operator of the server allowing downloading.

If you want use Asset Downloader without dedicated server (for example with archive.org) you should use "raw file list and url prefix" mode.

Show the full command you are using and the first 5 lines of the path list file that caused the "no content length in response error"

**Comment by ThePartyGoat224** [comment]
thanks for replying!

terminal command used: 
./AssetsDownloader.py --url-prefix https://web.archive.org/web/20230713000000id --path-list cdx.json

cdx.json: 
[["original"],
["https://s3.amazonaws.com/origin.ka.cdn/DWADragonsUnity/WIN/3.31.0/High/data/AdData.xml"],
["https://s3.amazonaws.com/origin.ka.cdn/DWADragonsUnity/WIN/3.31.0/High/data/ambershadertexturesdo"],
["https://s3.amazonaws.com/origin.ka.cdn/DWADragonsUnity/WIN/3.31.0/High/data/anidwdragonsimcoghelp.de-de"],
["https://s3.amazonaws.com/origin.ka.cdn/DWADragonsUnity/WIN/3.31.0/High/data/anidwdragonsimcoghelp.es-mx"],

**Comment by rpaciorek** [comment]
see example on https://github.com/SoDOff-Project/sodoff-tools?tab=readme-ov-file#path-list-mode

* path list should be plain text (one path per line), not json
* you should use `_` after `id` in archive.org url to download unmodified text files
* you need `/` at end of url-prefix or at beginning of path (AssetsDownloader uses string concatenation, not path concatenation for this)

**Comment by ThePartyGoat224** [comment]
thank you
